# -*- coding: utf-8 -*-
"""DAApractical2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ByayyXspgYGKikX74DLA65CmVgWuyB2S
"""

import time

# Function for Linear Search
def linear_search(arr, key):
    for i in range(len(arr)):
        if arr[i] == key:
            return i
    return -1

# User input
n = int(input("Enter the number of elements: "))

arr = []
print("Enter the elements:")
for i in range(n):
    arr.append(int(input()))

key = int(input("Enter the element to search: "))

# Start execution time
start_time = time.time()

# Perform Linear Search
result = linear_search(arr, key)

# End execution time
end_time = time.time()

# Display result
if result != -1:
    print(f"Element found at index {result}")
else:
    print("Element not found")

# Execution time
execution_time = end_time - start_time
print(f"Execution Time: {execution_time:.10f} seconds")

# Time Complexity
print("\nTime Complexity:")
print("Best Case   : O(1)")
print("Average Case: O(n)")
print("Worst Case  : O(n)")
print("Space Complexity: O(1)")

import time

# Function for Binary Search
def binary_search(arr, key):
    low = 0
    high = len(arr) - 1

    while low <= high:
        mid = (low + high) // 2

        if arr[mid] == key:
            return mid
        elif arr[mid] < key:
            low = mid + 1
        else:
            high = mid - 1

    return -1

# User input
n = int(input("Enter the number of elements: "))

arr = []
print("Enter the elements in sorted order:")
for i in range(n):
    arr.append(int(input()))

key = int(input("Enter the element to search: "))

# Start execution time
start_time = time.time()

# Perform Binary Search
result = binary_search(arr, key)

# End execution time
end_time = time.time()

# Display result
if result != -1:
    print(f"Element found at index {result}")
else:
    print("Element not found")

# Execution time
execution_time = end_time - start_time
print(f"Execution Time: {execution_time:.10f} seconds")

# Time Complexity
print("\nTime Complexity:")
print("Best Case   : O(1)")
print("Average Case: O(log n)")
print("Worst Case  : O(log n)")
print("Space Complexity: O(1)")